export const STRING_NUMBERS = [
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
];
export const NUMBERS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
export const SPECIAL_CHARACTERS = [
  '.',
  '*',
  '/',
  '-',
  ';',
  '{',
  '}',
  '[',
  ']',
  '?',
  '\\',
  '+',
  ':',
  '`',
  '~',
  '_',
  '=',
  '!',
  '@',
  '#',
  '$',
  '%',
  '^',
  '&',
  '*',
  '(',
  ')',
  '|',
  ',',
  ' ',
];
export const LOWERCASE_LETTERS = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
];
export const UPPERCASE_LETTERS = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];
export const WEEK_DAYS = [
  'sunday',
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
];
export const RESERVED_NAMES = ['CON', 'PRN', 'NUL', 'COM1', 'LPT1'];
export const MAX_IMAGE_FILE_SIZE_IN_BYTES = 1024 * 1024 * 5;
export const MAX_VIDEO_FILE_SIZE_IN_BYTES = 1024 * 1024 * 25;
export const MAX_DOCUMENT_FILE_SIZE_IN_BYTES = 1024 * 1024 * 1;
export const MAX_VOICE_FILE_SIZE_IN_BYTES = 1024 * 1024 * 10;

export const ALLOWED_IMAGE_FORMATS = [
  '.png',
  '.jpeg',
  '.bmp',
  '.jpg',
  '.PNG',
  '.JPEG',
  '.BMP',
  '.JPG',
];
export const ALLOWED_VIDEO_FORMATS = ['.mp4', '.mov', 'm4a'];
export const ALLOWED_DOCUMENT_FORMATS = [
  '.pdf',
  '.docs',
  '.docx',
  '.doc',
  '.pptx',
  '.PDF',
  '.DOCS',
  '.DOCX',
  '.DOC',
  '.PPTX',
  '.png',
  '.jpeg',
  '.bmp',
  '.jpg',
  '.PNG',
  '.JPEG',
  '.BMP',
  '.JPG',
];
export const ALLOWED_VOICE_FORMATS = ['.mp3'];

export const GLOBAL_VALIDATION = {
  EMAIL: { MIN_LENGTH: 5, MAX_LENGTH: 320 },
  PHONE_NUMBER: { MIN_LENGTH: 5, MAX_LENGTH: 20 },
  NAME: { MIN_LENGTH: 2, MAX_LENGTH: 220 },
  FILE_NAME: { MIN_LENGTH: 1, MAX_LENGTH: 400 },
  DESCRIPTION: { MIN_LENGTH: 10, MAX_LENGTH: 2200 },
  URL: { MIN_LENGTH: 3, MAX_LENGTH: 2048 },
  LAT: { MIN: -90, MAX: 90 },
  MESSAGE: { MIN_LENGTH: 10, MAX_LENGTH: 1000 },
  LON: { MIN: -180, MAX: 180 },
  PASSWORD: { MAX_LENGTH: 30, MIN_LENGTH: 8 },
  OTPS: {
    VALUE: { MIN_LENGTH: 6, MAX_LENGTH: 6 },
    EXPIRY: { MIN_LENGTH: 29, MAX_LENGTH: 29 },
  },
  TOKENS: { EXPIRY: { MIN_LENGTH: 29, MAX_LENGTH: 29 } },
  USERNAME: { MIN_LENGTH: 2, MAX_LENGTH: 30 },
  TEXT: { MAX_LENGTH: 100 },
  PERCENTAGE: { MAX: 100, MIN: 0 },
  TIME: {
    MIN_LENGTH: 7,
    MAX_LENGTH: 7,
  },
  DATE: {
    MIN_LENGTH: 10,
    MAX_LENGTH: 10,
  },
  BIO: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 175,
  },
  POINTS: {
    MIN: 0,
    MAX: 100000,
  },
};

export const MAGIC_VALUES = {
  EMPTY_PROP: 'Empty Prop',
};
export const PLACEHOLDERS = {
  REGISTER_FIRST: 'registerFirst',
  ALL_DAY_LONG: 'allDayLong',
};
